### ISSUE TITLE
release 1.6.0

### ISSUE THREAD

**Issue by cosmo0920** [cosmo0920/win32-api#19]
- [x] Support Ruby 2.3.0 (both of 32 bit and 64 bit versions)
- [x] Add AppVeyor CI support (building and testing)
  - [x] Change Ruby 2.0.0 installation paths
      + [x] Ruby 2.0.0 x86 should be placed at `C:\Ruby200\bin`
      + [x] Ruby 2.0.0 x64 should be placed at `C:\Ruby200-x64\bin`
- [x] Bump up version to 1.6.0
  * Because #18 drops Ruby 1.8.7 and 1.9.3. So, it should be treated as major version up.
- [x] Add [CHANGES](https://github.com/cosmo0920/win32-api/blob/master/CHANGES) entry for 1.6.0
- [x] Remove maintainer wanted! section from README
- [x] Push win32-api-1.6.0-universal-mingw32.gem to rubygems
- [x] Add `win32-api-1.6.0` tag

**Comment by djberg96** [comment]
👍 LGTM

**Comment by cosmo0920** [comment]
I've got success building at AppVeyor: https://ci.appveyor.com/project/cosmo0920/win32-api/build/3/job/19huucq8ilt3lgwa
I'll send a PR which contains AppVeyor support and adjust Ruby 2.0.0 path and so on in a few days.

**Comment by cosmo0920** [comment]
Done!
https://rubygems.org/gems/win32-api/versions/1.6.0-universal-mingw32
