### ISSUE TITLE
Getting-Started wiki page small typo

### ISSUE THREAD

**Issue by rgr78** [cosmo0920/win32-api#22]
There is a small typo in the wiki, page Getting-Started.

The line
dwptr  = [**buf**.size].pack('L') # This effectively gives us a pointer address

should be
dwptr  = [**buffer**.size].pack('L') # This effectively gives us a pointer address

otherwise the code won't run as is.

**Comment by cosmo0920** [comment]
I've fixed this on the revision: https://github.com/cosmo0920/win32-api/wiki/Getting-Started/bd99e4ab1306b128f4db8a404eeb04e8f2172ea4

Thanks for the report!
