### ISSUE TITLE
Appveyor.yml

### ISSUE THREAD

**Issue by MSP-Greg** [cosmo0920/win32-api#33]
Saw mention in [Ruby bug 13746](https://bugs.ruby-lang.org/issues/13746).  I'm not sure, but I think that the appveyor.yml file could be simplified a bit if one added `rdevkit` as a parameter to the rake commands, ie

```
bundle exec rake test:all
```
with
```
bundle exec rake -rdevkit test:all
```

Since `rdevkit` should set up the compile env for all versions...

I could look at a PR.  Interested in adding a trunk build?

**Comment by cosmo0920** [comment]
I want to use a command that is nearly normal use case.
Which command is preferred for users?

**Comment by MSP-Greg** [comment]
Most don't build directly from repos, and using 'gem install' sets compiler settings without the user needing to do anything.

In appveyor.yml files, it's used in ruby/openssl, puma/puma, sparklemotion/nokogiri, which is just a few that I checked...

**Comment by MSP-Greg** [comment]
I'll do a PR for appveyor, but maybe not tonite (-0600).

Want to add trunk?

RubyGems and Puma test with it.  It is my build.  Results shown [here](https://msp-greg.github.io/file.mingw_test-all.html).  I'll do the PR either way.

**Comment by cosmo0920** [comment]
Yes, please.
Thank you for notifying how to reduce appveypr.yml complexity.

**Comment by MSP-Greg** [comment]
I ended up here while trying to decide whether to write an API based fix for a vendor's bug.  Decided against it, but noticed this could be closed (?)

Seems like Appveyor is stable and working.  Feel free to ping me if any issues arise.

Thanks, Greg
